import { LayerConfig, Framework } from '@/types/neural-network';

// Calculate total parameters
export function calculateParameters(layers: LayerConfig[]): number {
  if (layers.length < 2) return 0;
  let total = 0;
  for (let i = 1; i < layers.length; i++) {
    const prevNeurons = layers[i - 1].neurons;
    const currNeurons = layers[i].neurons;
    total += prevNeurons * currNeurons + currNeurons; // weights + biases
  }
  return total;
}

// Generate PyTorch code
export function generatePyTorchCode(layers: LayerConfig[], className: string): string {
  const totalParams = calculateParameters(layers);
  const hasMultipleLayers = layers.length > 1;
  
  let code = `"""
Neural Network Model - Generated by Neural Network Visualizer
Framework: PyTorch
Total Layers: ${layers.length}
Total Parameters: ${totalParams.toLocaleString()}
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class ${className}(nn.Module):
    def __init__(self):
        super(${className}, self).__init__()
`;

  // Layer definitions
  if (layers.length === 1) {
    code += `        # Single layer with ${layers[0].neurons} feature${layers[0].neurons !== 1 ? 's' : ''}\n`;
    code += `        # Add more layers to create a neural network\n`;
  } else {
    layers.forEach((layer, idx) => {
      if (idx === 0) {
        code += `        # Input layer: ${layer.neurons} features\n`;
      } else {
        const prevNeurons = layers[idx - 1].neurons;
        const isOutput = idx === layers.length - 1;
        code += `        self.fc${idx} = nn.Linear(${prevNeurons}, ${layer.neurons})${isOutput ? '  # Output' : ''}\n`;
      }
    });
  }

  code += `
    def forward(self, x):
`;

  // Forward pass
  if (layers.length === 1) {
    code += `        # Pass-through (single layer)\n`;
    code += `        return x\n`;
  } else {
    for (let idx = 1; idx < layers.length; idx++) {
      const isOutput = idx === layers.length - 1;
      
      code += `        x = self.fc${idx}(x)\n`;
      
      if (isOutput) {
        code += `        x = F.softmax(x, dim=-1)  # Output activation\n`;
      } else {
        code += `        x = F.relu(x)\n`;
      }
    }
    code += `        return x\n`;
  }

  code += `
# Model instantiation
def create_model():
    """Create and return the model with default settings."""
    model = ${className}()
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    return model, criterion, optimizer

if __name__ == "__main__":
    model, criterion, optimizer = create_model()
    print(f"Model: {model.__class__.__name__}")
    print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")
    
    # Test forward pass
    dummy_input = torch.randn(1, ${layers[0].neurons})
    output = model(dummy_input)
    print(f"Input shape: {dummy_input.shape}")
    print(f"Output shape: {output.shape}")
`;

  return code;
}

// Generate TensorFlow/Keras code
export function generateTensorFlowCode(layers: LayerConfig[], className: string): string {
  const totalParams = calculateParameters(layers);
  
  let code = `"""
Neural Network Model - Generated by Neural Network Visualizer
Framework: TensorFlow / Keras
Total Layers: ${layers.length}
Total Parameters: ${totalParams.toLocaleString()}
"""

import tensorflow as tf
from tensorflow.keras import layers, Model

class ${className}(Model):
    def __init__(self):
        super(${className}, self).__init__()
`;

  // Layer definitions
  if (layers.length === 1) {
    code += `        # Single layer with ${layers[0].neurons} feature${layers[0].neurons !== 1 ? 's' : ''}\n`;
    code += `        # Add more layers to create a neural network\n`;
  } else {
    layers.forEach((layer, idx) => {
      if (idx === 0) {
        code += `        # Input: ${layer.neurons} features\n`;
      } else {
        const isOutput = idx === layers.length - 1;
        const activation = isOutput ? 'softmax' : 'relu';
        code += `        self.dense_${idx} = layers.Dense(${layer.neurons}, activation='${activation}'${isOutput ? '  # Output' : ''})\n`;
      }
    });
  }

  code += `
    def call(self, x):
`;

  // Forward pass
  if (layers.length === 1) {
    code += `        # Pass-through (single layer)\n`;
    code += `        return x\n`;
  } else {
    for (let idx = 1; idx < layers.length; idx++) {
      code += `        x = self.dense_${idx}(x)\n`;
    }
    code += `        return x\n`;
  }

  code += `
# Model creation
def create_model():
    """Create and compile the model."""
    model = ${className}()
    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

if __name__ == "__main__":
    model = create_model()
    
    # Build the model
    model.build((None, ${layers[0].neurons}))
    model.summary()
`;

  return code;
}

// Generate JAX/Flax code
export function generateJAXCode(layers: LayerConfig[], className: string): string {
  const totalParams = calculateParameters(layers);
  const features = layers.length > 1 ? layers.slice(1).map(l => l.neurons) : [];
  
  let code = `"""
Neural Network Model - Generated by Neural Network Visualizer
Framework: JAX / Flax
Total Layers: ${layers.length}
Total Parameters: ${totalParams.toLocaleString()}
"""

import jax
import jax.numpy as jnp
import flax.linen as nn
from typing import Sequence

class ${className}(nn.Module):
    """Neural Network Model"""
    features: Sequence[int] = (${features.join(', ')},)
    
    @nn.compact
    def __call__(self, x):
`;

  // Forward pass
  if (layers.length === 1) {
    code += `        # Single layer - pass-through\n`;
    code += `        # Add more layers to create a neural network\n`;
    code += `        return x\n`;
  } else {
    for (let idx = 1; idx < layers.length; idx++) {
      const isOutput = idx === layers.length - 1;
      
      if (isOutput) {
        code += `        x = nn.Dense(self.features[${idx - 1}])(x)\n`;
        code += `        x = nn.softmax(x)  # Output activation\n`;
      } else {
        code += `        x = nn.Dense(self.features[${idx - 1}])(x)\n`;
        code += `        x = nn.relu(x)\n`;
      }
    }
    code += `        return x\n`;
  }

  code += `
# Training setup
from flax.training import train_state
import optax

def create_train_state(rng, learning_rate=0.001):
    """Create initial training state."""
    model = ${className}()
    params = model.init(rng, jnp.ones([1, ${layers[0].neurons}]))['params']
    tx = optax.adam(learning_rate)
    return train_state.TrainState.create(
        apply_fn=model.apply,
        params=params,
        tx=tx
    )

if __name__ == "__main__":
    rng = jax.random.PRNGKey(0)
    state = create_train_state(rng)
    
    # Count parameters
    param_count = sum(x.size for x in jax.tree_util.tree_leaves(state.params))
    print(f"Model: ${className}")
    print(f"Parameters: {param_count:,}")
    
    # Test forward pass
    test_input = jnp.ones([1, ${layers[0].neurons}])
    output = state.apply_fn({'params': state.params}, test_input)
    print(f"Input shape: {test_input.shape}")
    print(f"Output shape: {output.shape}")
`;

  return code;
}

// Get code for framework
export function getCode(layers: LayerConfig[], framework: Framework, className: string): string {
  switch (framework) {
    case 'pytorch':
      return generatePyTorchCode(layers, className);
    case 'tensorflow':
      return generateTensorFlowCode(layers, className);
    case 'jax':
      return generateJAXCode(layers, className);
    default:
      return generatePyTorchCode(layers, className);
  }
}

// Get file extension
export function getFileExtension(framework: Framework): string {
  return 'py';
}

// Get filename
export function getFileName(framework: Framework, className: string): string {
  const ext = getFileExtension(framework);
  const prefix = framework === 'pytorch' ? 'model_pytorch' : 
                 framework === 'tensorflow' ? 'model_tensorflow' : 
                 'model_jax';
  return `${prefix}.${ext}`;
}
