'use client';

import React, { useMemo, useState } from 'react';
import { useNeuralNetworkStore } from '@/store/neural-network-store';
import { Framework, NeuralLayer } from '@/types/neural-network';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Code2, Copy, Download, ChevronDown, ChevronRight, Check, FileCode } from 'lucide-react';
import { toast } from 'sonner';

interface CodeSectionProps {
  isExpanded: boolean;
  onToggle: () => void;
}

const FRAMEWORKS: { value: Framework; label: string; extension: string }[] = [
  { value: 'pytorch', label: 'PyTorch', extension: 'py' },
  { value: 'tensorflow', label: 'TensorFlow', extension: 'py' },
  { value: 'jax', label: 'JAX', extension: 'py' },
];

// PyTorch Code Generator
function generatePyTorchCode(layers: NeuralLayer[], className: string, includeTraining: boolean, includeComments: boolean): string {
  let code = '';
  
  if (includeComments) {
    code += `"""
Neural Network Model
Generated by Neural Network Visualizer
Framework: PyTorch
Total Layers: ${layers.length}
Total Parameters: ${calculateParameters(layers).toLocaleString()}
"""
`;
  }
  
  code += `import torch
import torch.nn as nn
import torch.nn.functional as F
`;

  if (includeTraining) {
    code += `import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
`;
  }

  code += `

class ${className}(nn.Module):
    def __init__(self):
        super(${className}, self).__init__()
`;

  // Layer definitions
  let denseIdx = 1;
  let convIdx = 1;
  let poolIdx = 1;
  let bnIdx = 1;
  let lstmIdx = 1;
  let gruIdx = 1;
  let dropoutIdx = 1;

  layers.forEach((layer, idx) => {
    if (includeComments && layer.type !== 'input') {
      code += `        # ${layer.name}\n`;
    }

    switch (layer.type) {
      case 'dense':
        const prevUnits = idx > 0 ? layers[idx - 1]?.units || 64 : layers[0]?.units || 784;
        code += `        self.fc${denseIdx} = nn.Linear(${prevUnits}, ${layer.units}, bias=${layer.useBias !== false})\n`;
        denseIdx++;
        break;
      case 'conv2d':
        const inChannels = idx === 0 ? 1 : (layers[idx - 1]?.filters || 32);
        code += `        self.conv${convIdx} = nn.Conv2d(${inChannels}, ${layer.filters}, kernel_size=${JSON.stringify(layer.kernelSize || [3, 3])}, stride=${JSON.stringify(layer.stride || [1, 1])}, padding=${layer.padding === 'same' ? 1 : 0})\n`;
        convIdx++;
        break;
      case 'maxpool2d':
        code += `        self.pool${poolIdx} = nn.MaxPool2d(kernel_size=${JSON.stringify(layer.kernelSize || [2, 2])})\n`;
        poolIdx++;
        break;
      case 'avgpool2d':
        code += `        self.pool${poolIdx} = nn.AvgPool2d(kernel_size=${JSON.stringify(layer.kernelSize || [2, 2])})\n`;
        poolIdx++;
        break;
      case 'dropout':
        code += `        self.dropout${dropoutIdx} = nn.Dropout(p=${layer.dropout || 0.5})\n`;
        dropoutIdx++;
        break;
      case 'batchnorm':
        const numFeatures = layers[idx - 1]?.filters || layers[idx - 1]?.units || 64;
        code += `        self.bn${bnIdx} = nn.BatchNorm1d(${numFeatures})\n`;
        bnIdx++;
        break;
      case 'lstm':
        const lstmInputSize = idx > 0 ? layers[idx - 1]?.units || 128 : 128;
        code += `        self.lstm${lstmIdx} = nn.LSTM(${lstmInputSize}, ${layer.units}, batch_first=True)\n`;
        lstmIdx++;
        break;
      case 'gru':
        const gruInputSize = idx > 0 ? layers[idx - 1]?.units || 128 : 128;
        code += `        self.gru${gruIdx} = nn.GRU(${gruInputSize}, ${layer.units}, batch_first=True)\n`;
        gruIdx++;
        break;
      case 'flatten':
        code += `        self.flatten = nn.Flatten()\n`;
        break;
    }
  });

  code += `
    def forward(self, x):
`;

  // Forward pass
  denseIdx = 1;
  convIdx = 1;
  poolIdx = 1;
  bnIdx = 1;
  lstmIdx = 1;
  gruIdx = 1;
  dropoutIdx = 1;
  let needsFlatten = false;

  layers.forEach((layer, idx) => {
    if (layer.type === 'input') return;

    switch (layer.type) {
      case 'dense':
        if (needsFlatten && !layers.slice(0, idx).some(l => l.type === 'flatten')) {
          code += `        x = x.view(x.size(0), -1)\n`;
          needsFlatten = false;
        }
        code += `        x = self.fc${denseIdx}(x)\n`;
        if (layer.activation && layer.activation !== 'linear') {
          const actFn = getActivationFn('pytorch', layer.activation);
          code += `        x = ${actFn}\n`;
        }
        denseIdx++;
        break;
      case 'conv2d':
        code += `        x = self.conv${convIdx}(x)\n`;
        if (layer.activation && layer.activation !== 'linear') {
          const actFn = getActivationFn('pytorch', layer.activation);
          code += `        x = ${actFn}\n`;
        }
        needsFlatten = true;
        convIdx++;
        break;
      case 'maxpool2d':
      case 'avgpool2d':
        code += `        x = self.pool${poolIdx}(x)\n`;
        poolIdx++;
        needsFlatten = true;
        break;
      case 'dropout':
        code += `        x = self.dropout${dropoutIdx}(x)\n`;
        dropoutIdx++;
        break;
      case 'batchnorm':
        code += `        x = self.bn${bnIdx}(x)\n`;
        bnIdx++;
        break;
      case 'lstm':
        code += `        x, _ = self.lstm${lstmIdx}(x)\n`;
        lstmIdx++;
        break;
      case 'gru':
        code += `        x, _ = self.gru${gruIdx}(x)\n`;
        gruIdx++;
        break;
      case 'flatten':
        code += `        x = self.flatten(x)\n`;
        needsFlatten = false;
        break;
    }
  });

  code += `        return x
`;

  if (includeTraining) {
    code += `

# Training Configuration
def create_model():
    model = ${className}()
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    return model, criterion, optimizer

def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    total_loss = 0
    correct = 0
    total = 0
    
    for batch_idx, (data, target) in enumerate(dataloader):
        data, target = data.to(device), target.to(device)
        
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        pred = output.argmax(dim=1)
        correct += (pred == target).sum().item()
        total += target.size(0)
    
    return total_loss / len(dataloader), correct / total

# Usage Example
if __name__ == "__main__":
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model, criterion, optimizer = create_model()
    model = model.to(device)
    print(f"Model created with {sum(p.numel() for p in model.parameters()):,} parameters")
`;
  }

  return code;
}

// TensorFlow Code Generator
function generateTensorFlowCode(layers: NeuralLayer[], className: string, includeTraining: boolean, includeComments: boolean): string {
  let code = '';
  
  if (includeComments) {
    code += `"""
Neural Network Model
Generated by Neural Network Visualizer
Framework: TensorFlow / Keras
Total Layers: ${layers.length}
Total Parameters: ${calculateParameters(layers).toLocaleString()}
"""
`;
  }
  
  code += `import tensorflow as tf
from tensorflow.keras import layers, Model
from tensorflow.keras.optimizers import Adam
`;

  code += `

class ${className}(Model):
    def __init__(self):
        super(${className}, self).__init__()
`;

  // Layer definitions
  let denseIdx = 1;
  let convIdx = 1;
  let poolIdx = 1;
  let bnIdx = 1;
  let lstmIdx = 1;
  let gruIdx = 1;
  let dropoutIdx = 1;

  layers.forEach((layer, idx) => {
    if (layer.type === 'input') return;
    
    if (includeComments) {
      code += `        # ${layer.name}\n`;
    }

    switch (layer.type) {
      case 'dense':
        code += `        self.dense_${denseIdx} = layers.Dense(${layer.units}, activation='${layer.activation}'${layer.useBias === false ? ', use_bias=False' : ''})\n`;
        denseIdx++;
        break;
      case 'conv2d':
        code += `        self.conv_${convIdx} = layers.Conv2D(${layer.filters}, ${JSON.stringify(layer.kernelSize || [3, 3])}, activation='${layer.activation}', padding='${layer.padding || 'same'}')\n`;
        convIdx++;
        break;
      case 'maxpool2d':
        code += `        self.pool_${poolIdx} = layers.MaxPooling2D(${JSON.stringify(layer.kernelSize || [2, 2])})\n`;
        poolIdx++;
        break;
      case 'avgpool2d':
        code += `        self.pool_${poolIdx} = layers.AveragePooling2D(${JSON.stringify(layer.kernelSize || [2, 2])})\n`;
        poolIdx++;
        break;
      case 'dropout':
        code += `        self.dropout_${dropoutIdx} = layers.Dropout(${layer.dropout || 0.5})\n`;
        dropoutIdx++;
        break;
      case 'batchnorm':
        code += `        self.bn_${bnIdx} = layers.BatchNormalization()\n`;
        bnIdx++;
        break;
      case 'lstm':
        code += `        self.lstm_${lstmIdx} = layers.LSTM(${layer.units}, return_sequences=True)\n`;
        lstmIdx++;
        break;
      case 'gru':
        code += `        self.gru_${gruIdx} = layers.GRU(${layer.units}, return_sequences=True)\n`;
        gruIdx++;
        break;
      case 'flatten':
        code += `        self.flatten = layers.Flatten()\n`;
        break;
    }
  });

  code += `
    def call(self, x, training=False):
`;

  // Forward pass
  denseIdx = 1;
  convIdx = 1;
  poolIdx = 1;
  bnIdx = 1;
  lstmIdx = 1;
  gruIdx = 1;
  dropoutIdx = 1;

  layers.forEach((layer) => {
    if (layer.type === 'input') return;

    switch (layer.type) {
      case 'dense':
        code += `        x = self.dense_${denseIdx}(x)\n`;
        denseIdx++;
        break;
      case 'conv2d':
        code += `        x = self.conv_${convIdx}(x)\n`;
        convIdx++;
        break;
      case 'maxpool2d':
      case 'avgpool2d':
        code += `        x = self.pool_${poolIdx}(x)\n`;
        poolIdx++;
        break;
      case 'dropout':
        code += `        x = self.dropout_${dropoutIdx}(x, training=training)\n`;
        dropoutIdx++;
        break;
      case 'batchnorm':
        code += `        x = self.bn_${bnIdx}(x, training=training)\n`;
        bnIdx++;
        break;
      case 'lstm':
        code += `        x = self.lstm_${lstmIdx}(x)\n`;
        lstmIdx++;
        break;
      case 'gru':
        code += `        x = self.gru_${gruIdx}(x)\n`;
        gruIdx++;
        break;
      case 'flatten':
        code += `        x = self.flatten(x)\n`;
        break;
    }
  });

  code += `        return x
`;

  if (includeTraining) {
    code += `

# Model Creation and Training
def create_and_compile_model():
    model = ${className}()
    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# Usage Example
if __name__ == "__main__":
    model = create_and_compile_model()
    
    # Build the model with input shape
    input_shape = (None, ${layers[0]?.units || 784})
    model.build(input_shape)
    model.summary()
`;
  }

  return code;
}

// JAX Code Generator
function generateJAXCode(layers: NeuralLayer[], className: string, includeTraining: boolean, includeComments: boolean): string {
  let code = '';
  
  if (includeComments) {
    code += `"""
Neural Network Model
Generated by Neural Network Visualizer
Framework: JAX / Flax
Total Layers: ${layers.length}
Total Parameters: ${calculateParameters(layers).toLocaleString()}
"""
`;
  }
  
  code += `import jax
import jax.numpy as jnp
import flax.linen as nn
from typing import Sequence
`;

  code += `

class ${className}(nn.Module):
    """Neural Network Model"""
`;

  // Add layer configuration
  const denseLayers = layers.filter(l => l.type === 'dense' || l.type === 'output');
  if (denseLayers.length > 0) {
    code += `    features: Sequence[int] = (${denseLayers.map(l => l.units).join(', ')},)\n`;
  }
  
  code += `
    @nn.compact
    def __call__(self, x, training: bool = True):
`;

  // Forward pass
  let dropoutRate = 0;
  layers.forEach((layer) => {
    if (layer.type === 'input') return;
    
    if (includeComments) {
      code += `        # ${layer.name}\n`;
    }

    switch (layer.type) {
      case 'dense':
        code += `        x = nn.Dense(${layer.units})(x)\n`;
        if (layer.activation && layer.activation !== 'linear') {
          const actFn = getActivationFn('jax', layer.activation);
          code += `        x = ${actFn}\n`;
        }
        break;
      case 'conv2d':
        code += `        x = nn.Conv(${layer.filters}, kernel_size=${JSON.stringify(layer.kernelSize || [3, 3])})(x)\n`;
        if (layer.activation && layer.activation !== 'linear') {
          const actFn = getActivationFn('jax', layer.activation);
          code += `        x = ${actFn}\n`;
        }
        break;
      case 'dropout':
        dropoutRate = layer.dropout || 0.5;
        code += `        x = nn.Dropout(rate=${dropoutRate})(x, deterministic=not training)\n`;
        break;
      case 'batchnorm':
        code += `        x = nn.BatchNorm(use_running_average=not training)(x)\n`;
        break;
      case 'flatten':
        code += `        x = x.reshape((x.shape[0], -1))\n`;
        break;
      default:
        code += `        # ${layer.type} layer\n`;
    }
  });

  code += `        return x
`;

  if (includeTraining) {
    code += `

# Training Setup
from flax.training import train_state
import optax

def create_train_state(rng, learning_rate=0.001):
    """Creates initial training state."""
    model = ${className}()
    params = model.init(rng, jnp.ones([1, ${layers[0]?.units || 784}]))['params']
    tx = optax.adam(learning_rate)
    return train_state.TrainState.create(apply_fn=model.apply, params=params, tx=tx)

@jax.jit
def train_step(state, batch, labels):
    """Performs a single training step."""
    def loss_fn(params):
        logits = state.apply_fn({'params': params}, batch)
        loss = jax.vmap(jax.nn.softmax_cross_entropy_with_integer_labels)(logits, labels).mean()
        return loss, logits
    
    grad_fn = jax.value_and_grad(loss_fn, has_aux=True)
    (loss, logits), grads = grad_fn(state.params)
    state = state.apply_gradients(grads=grads)
    accuracy = jnp.mean(jnp.argmax(logits, axis=-1) == labels)
    return state, loss, accuracy

# Usage Example
if __name__ == "__main__":
    rng = jax.random.PRNGKey(0)
    state = create_train_state(rng)
    print(f"Model initialized with {sum(x.size for x in jax.tree_util.tree_leaves(state.params)):,} parameters")
`;
  }

  return code;
}

function getActivationFn(framework: string, activation: string): string {
  const fns: Record<string, Record<string, string>> = {
    pytorch: {
      relu: 'F.relu(x)',
      sigmoid: 'torch.sigmoid(x)',
      tanh: 'torch.tanh(x)',
      softmax: 'F.softmax(x, dim=-1)',
      leaky_relu: 'F.leaky_relu(x, 0.01)',
      gelu: 'F.gelu(x)',
      swish: 'x * torch.sigmoid(x)',
    },
    jax: {
      relu: 'nn.relu(x)',
      sigmoid: 'jax.nn.sigmoid(x)',
      tanh: 'jax.nn.tanh(x)',
      softmax: 'jax.nn.softmax(x)',
      leaky_relu: 'jax.nn.leaky_relu(x)',
      gelu: 'jax.nn.gelu(x)',
      swish: 'jax.nn.swish(x)',
    },
  };
  return fns[framework]?.[activation] || fns[framework]?.relu || 'x';
}

function calculateParameters(layers: NeuralLayer[]): number {
  let total = 0;
  layers.forEach((layer, idx) => {
    if (layer.type === 'dense' && idx > 0) {
      const prevUnits = layers[idx - 1]?.units || 0;
      total += prevUnits * layer.units + (layer.useBias !== false ? layer.units : 0);
    }
  });
  return total;
}

export function CodeSection({ isExpanded, onToggle }: CodeSectionProps) {
  const { codeOptions, setCodeOptions, network, viewMode } = useNeuralNetworkStore();
  const [copied, setCopied] = useState(false);
  const [activeFramework, setActiveFramework] = useState<Framework>('pytorch');

  // Generate code for all frameworks
  const code = useMemo(() => {
    switch (activeFramework) {
      case 'pytorch':
        return generatePyTorchCode(
          network.layers,
          codeOptions.className,
          codeOptions.includeTraining,
          codeOptions.includeComments
        );
      case 'tensorflow':
        return generateTensorFlowCode(
          network.layers,
          codeOptions.className,
          codeOptions.includeTraining,
          codeOptions.includeComments
        );
      case 'jax':
        return generateJAXCode(
          network.layers,
          codeOptions.className,
          codeOptions.includeTraining,
          codeOptions.includeComments
        );
      default:
        return '';
    }
  }, [network.layers, codeOptions.className, codeOptions.includeTraining, codeOptions.includeComments, activeFramework]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    toast.success('Code copied to clipboard!');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const framework = FRAMEWORKS.find(f => f.value === activeFramework);
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${codeOptions.className.toLowerCase()}.${framework?.extension || 'py'}`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Code downloaded!');
  };

  return (
    <div className="border-b border-white/5">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-white/[0.02] transition-colors"
      >
        <div className="flex items-center gap-2">
          <FileCode className="w-4 h-4 text-gray-400" />
          <span className="text-sm font-medium text-white">Model Code</span>
        </div>
        {isExpanded ? (
          <ChevronDown className="w-4 h-4 text-gray-500" />
        ) : (
          <ChevronRight className="w-4 h-4 text-gray-500" />
        )}
      </button>
      
      {isExpanded && (
        <div className="px-4 pb-4 space-y-3">
          {/* Framework Tabs */}
          <div className="flex gap-1 bg-white/5 rounded-lg p-1">
            {FRAMEWORKS.map(fw => (
              <button
                key={fw.value}
                onClick={() => setActiveFramework(fw.value)}
                className={`flex-1 px-3 py-1.5 text-xs rounded-md transition-colors ${
                  activeFramework === fw.value
                    ? 'bg-violet-500 text-white'
                    : 'text-gray-400 hover:text-white'
                }`}
              >
                {fw.label}
              </button>
            ))}
          </div>

          {/* Options */}
          <div className="flex items-center gap-4">
            <div className="flex items-center justify-between flex-1">
              <Label className="text-xs text-gray-400">Include Training</Label>
              <Switch
                checked={codeOptions.includeTraining}
                onCheckedChange={(checked) => setCodeOptions({ includeTraining: checked })}
              />
            </div>
            <div className="flex items-center justify-between flex-1">
              <Label className="text-xs text-gray-400">Comments</Label>
              <Switch
                checked={codeOptions.includeComments}
                onCheckedChange={(checked) => setCodeOptions({ includeComments: checked })}
              />
            </div>
          </div>

          {/* Code Display */}
          <div className="relative">
            <ScrollArea className="h-[280px] rounded-lg bg-[#0d0d12] border border-white/5">
              <pre className="p-3 text-xs font-mono text-gray-300 leading-relaxed">
                <code>{code}</code>
              </pre>
            </ScrollArea>
            
            {/* Action Buttons */}
            <div className="absolute top-2 right-2 flex gap-1">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopy}
                className="h-7 px-2 text-xs bg-black/40 hover:bg-black/60 text-gray-300"
              >
                {copied ? <Check className="w-3 h-3 mr-1 text-green-400" /> : <Copy className="w-3 h-3 mr-1" />}
                {copied ? 'Copied' : 'Copy'}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleDownload}
                className="h-7 px-2 text-xs bg-black/40 hover:bg-black/60 text-gray-300"
              >
                <Download className="w-3 h-3 mr-1" />
                Save
              </Button>
            </div>
          </div>

          {/* Stats */}
          <div className="flex items-center justify-between text-[10px] text-gray-500 pt-1">
            <span>{network.layers.length} layers</span>
            <span>{calculateParameters(network.layers).toLocaleString()} parameters</span>
          </div>
        </div>
      )}
    </div>
  );
}
