'use client';

import React, { useMemo } from 'react';
import { useNeuralNetworkStore } from '@/store/neural-network-store';
import { NeuralLayer, Framework, CodeGenerationOptions } from '@/types/neural-network';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Code2, Copy, Download, FileCode, Settings, Check } from 'lucide-react';
import { toast } from 'sonner';

const generatePyTorchCode = (layers: NeuralLayer[], options: CodeGenerationOptions): string => {
  const { className, includeComments, includeTraining } = options;
  
  let code = '';
  
  if (includeComments) {
    code += `"""
Neural Network Architecture
Generated by Neural Network Visualizer
Framework: PyTorch
"""
`;
  }
  
  code += `import torch
import torch.nn as nn
`;

  if (includeTraining) {
    code += `import torch.optim as optim
`;
  }

  code += `

class ${className}(nn.Module):
    def __init__(self):
        super(${className}, self).__init__()
`;
  
  // Define layers
  let layerIdx = 1;
  layers.forEach((layer, idx) => {
    if (layer.type === 'input') return;
    
    if (includeComments) {
      code += `        # ${layer.name}\n`;
    }
    
    switch (layer.type) {
      case 'dense':
        const prevUnits = layers[idx - 1]?.units || 784;
        code += `        self.fc${layerIdx} = nn.Linear(${prevUnits}, ${layer.units}, bias=${layer.useBias !== false})\n`;
        layerIdx++;
        break;
      case 'conv2d':
        const inChannels = idx === 1 ? 1 : (layers[idx - 1]?.filters || 32);
        code += `        self.conv${layerIdx} = nn.Conv2d(${inChannels}, ${layer.filters}, kernel_size=${JSON.stringify(layer.kernelSize || [3, 3])}, padding=${layer.padding === 'same' ? 1 : 0})\n`;
        layerIdx++;
        break;
      case 'maxpool2d':
        code += `        self.pool${layerIdx} = nn.MaxPool2d(kernel_size=${JSON.stringify(layer.kernelSize || [2, 2])})\n`;
        layerIdx++;
        break;
      case 'avgpool2d':
        code += `        self.pool${layerIdx} = nn.AvgPool2d(kernel_size=${JSON.stringify(layer.kernelSize || [2, 2])})\n`;
        layerIdx++;
        break;
      case 'dropout':
        code += `        self.dropout = nn.Dropout(${layer.dropout || 0.5})\n`;
        break;
      case 'batchnorm':
        const numFeatures = layers[idx - 1]?.filters || layers[idx - 1]?.units || 64;
        code += `        self.bn${layerIdx} = nn.BatchNorm1d(${numFeatures})\n`;
        break;
      case 'lstm':
        const inputSize = idx === 1 ? 128 : (layers[idx - 1]?.units || 64);
        code += `        self.lstm = nn.LSTM(${inputSize}, ${layer.units}, batch_first=True)\n`;
        break;
      case 'gru':
        const gruInputSize = idx === 1 ? 128 : (layers[idx - 1]?.units || 64);
        code += `        self.gru = nn.GRU(${gruInputSize}, ${layer.units}, batch_first=True)\n`;
        break;
      case 'flatten':
        code += `        self.flatten = nn.Flatten()\n`;
        break;
    }
  });

  code += `
    def forward(self, x):
`;
  
  // Forward pass
  let fcIdx = 1;
  let convIdx = 1;
  let poolIdx = 1;
  
  layers.forEach((layer, idx) => {
    if (layer.type === 'input') return;
    
    switch (layer.type) {
      case 'dense':
        if (layers[idx - 1]?.type === 'flatten' || layers[idx - 1]?.type === 'conv2d' || layers[idx - 1]?.type === 'maxpool2d') {
          code += `        x = x.view(x.size(0), -1)\n`;
        }
        code += `        x = self.fc${fcIdx}(x)\n`;
        if (layer.activation !== 'linear') {
          const act = layer.activation === 'leaky_relu' ? 'F.leaky_relu(x, 0.01)' : `torch.${layer.activation}(x)`;
          code += `        x = F.${layer.activation === 'leaky_relu' ? 'leaky_relu(x, 0.01)' : layer.activation}(x)\n`;
        }
        fcIdx++;
        break;
      case 'conv2d':
        code += `        x = self.conv${convIdx}(x)\n`;
        if (layer.activation !== 'linear') {
          code += `        x = F.${layer.activation === 'leaky_relu' ? 'leaky_relu(x, 0.01)' : layer.activation}(x)\n`;
        }
        convIdx++;
        break;
      case 'maxpool2d':
        code += `        x = self.pool${poolIdx}(x)\n`;
        poolIdx++;
        break;
      case 'avgpool2d':
        code += `        x = self.pool${poolIdx}(x)\n`;
        poolIdx++;
        break;
      case 'dropout':
        code += `        x = self.dropout(x)\n`;
        break;
      case 'batchnorm':
        code += `        x = self.bn${fcIdx > 1 ? fcIdx - 1 : convIdx}(x)\n`;
        break;
      case 'lstm':
        code += `        x, _ = self.lstm(x)\n`;
        break;
      case 'gru':
        code += `        x, _ = self.gru(x)\n`;
        break;
      case 'flatten':
        code += `        x = self.flatten(x)\n`;
        break;
    }
  });

  code += `        return x
`;

  if (includeTraining) {
    code += `

# Training setup
model = ${className}()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

def train(model, dataloader, epochs=10):
    model.train()
    for epoch in range(epochs):
        for batch_idx, (data, target) in enumerate(dataloader):
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output, target)
            loss.backward()
            optimizer.step()
            
            if batch_idx % 100 == 0:
                print(f'Epoch {epoch}, Batch {batch_idx}, Loss: {loss.item():.4f}')
`;
  }

  return code;
};

const generateTensorFlowCode = (layers: NeuralLayer[], options: CodeGenerationOptions): string => {
  const { className, includeComments, includeTraining } = options;
  
  let code = '';
  
  if (includeComments) {
    code += `"""
Neural Network Architecture
Generated by Neural Network Visualizer
Framework: TensorFlow/Keras
"""
`;
  }
  
  code += `import tensorflow as tf
from tensorflow.keras import layers, Model

`;

  if (includeComments) {
    code += `# Define the model architecture\n`;
  }
  
  code += `class ${className}(Model):
    def __init__(self):
        super(${className}, self).__init__()
`;

  // Define layers
  layers.forEach((layer, idx) => {
    if (layer.type === 'input') return;
    
    if (includeComments) {
      code += `        # ${layer.name}\n`;
    }
    
    switch (layer.type) {
      case 'dense':
        code += `        self.dense_${idx} = layers.Dense(${layer.units}, activation='${layer.activation}'${layer.useBias !== false ? '' : ', use_bias=False'})\n`;
        break;
      case 'conv2d':
        code += `        self.conv_${idx} = layers.Conv2D(${layer.filters}, ${JSON.stringify(layer.kernelSize || [3, 3])}, activation='${layer.activation}', padding='${layer.padding || 'same'}')\n`;
        break;
      case 'maxpool2d':
        code += `        self.pool_${idx} = layers.MaxPooling2D(${JSON.stringify(layer.kernelSize || [2, 2])})\n`;
        break;
      case 'avgpool2d':
        code += `        self.pool_${idx} = layers.AveragePooling2D(${JSON.stringify(layer.kernelSize || [2, 2])})\n`;
        break;
      case 'dropout':
        code += `        self.dropout = layers.Dropout(${layer.dropout || 0.5})\n`;
        break;
      case 'batchnorm':
        code += `        self.bn_${idx} = layers.BatchNormalization()\n`;
        break;
      case 'lstm':
        code += `        self.lstm = layers.LSTM(${layer.units}, return_sequences=True)\n`;
        break;
      case 'gru':
        code += `        self.gru = layers.GRU(${layer.units}, return_sequences=True)\n`;
        break;
      case 'flatten':
        code += `        self.flatten = layers.Flatten()\n`;
        break;
    }
  });

  code += `
    def call(self, x, training=False):
`;

  // Forward pass
  layers.forEach((layer, idx) => {
    if (layer.type === 'input') return;
    
    switch (layer.type) {
      case 'dense':
        code += `        x = self.dense_${idx}(x)\n`;
        break;
      case 'conv2d':
        code += `        x = self.conv_${idx}(x)\n`;
        break;
      case 'maxpool2d':
      case 'avgpool2d':
        code += `        x = self.pool_${idx}(x)\n`;
        break;
      case 'dropout':
        code += `        x = self.dropout(x, training=training)\n`;
        break;
      case 'batchnorm':
        code += `        x = self.bn_${idx}(x, training=training)\n`;
        break;
      case 'lstm':
        code += `        x = self.lstm(x)\n`;
        break;
      case 'gru':
        code += `        x = self.gru(x)\n`;
        break;
      case 'flatten':
        code += `        x = self.flatten(x)\n`;
        break;
    }
  });

  code += `        return x
`;

  if (includeTraining) {
    code += `

# Training setup
model = ${className}()
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
# model.fit(train_dataset, epochs=10, validation_data=val_dataset)
`;
  }

  return code;
};

const generateJAXCode = (layers: NeuralLayer[], options: CodeGenerationOptions): string => {
  const { className, includeComments } = options;
  
  let code = '';
  
  if (includeComments) {
    code += `"""
Neural Network Architecture
Generated by Neural Network Visualizer
Framework: JAX/Flax
"""
`;
  }
  
  code += `import jax
import jax.numpy as jnp
from flax import linen as nn
from typing import Sequence

class ${className}(nn.Module):
    features: Sequence[int]

    @nn.compact
    def __call__(self, x, training: bool = True):
`;

  layers.forEach((layer, idx) => {
    if (layer.type === 'input') return;
    
    if (includeComments) {
      code += `        # ${layer.name}\n`;
    }
    
    switch (layer.type) {
      case 'dense':
        code += `        x = nn.Dense(${layer.units})(x)\n`;
        if (layer.activation !== 'linear') {
          const actFn = layer.activation === 'relu' ? 'nn.relu' : 
                        layer.activation === 'sigmoid' ? 'jax.nn.sigmoid' :
                        layer.activation === 'tanh' ? 'jax.nn.tanh' :
                        layer.activation === 'softmax' ? 'jax.nn.softmax' : 'nn.relu';
          code += `        x = ${actFn}(x)\n`;
        }
        break;
      case 'dropout':
        code += `        x = nn.Dropout(rate=${layer.dropout || 0.5})(x, deterministic=not training)\n`;
        break;
      case 'batchnorm':
        code += `        x = nn.BatchNorm()(x, use_running_average=not training)\n`;
        break;
      default:
        code += `        # ${layer.type} layer\n`;
    }
  });

  code += `        return x

# Initialize model
model = ${className}(features=[${layers.filter(l => l.type === 'dense').map(l => l.units).join(', ')}])

# Example usage
# key = jax.random.PRNGKey(0)
# params = model.init(key, jnp.ones([1, ${layers[0]?.units || 784}]))
# output = model.apply(params, jnp.ones([1, ${layers[0]?.units || 784}]))
`;

  return code;
};

export function CodeGenerationPanel() {
  const { network, codeOptions, setCodeOptions } = useNeuralNetworkStore();
  const [copied, setCopied] = React.useState(false);

  const generatedCode = useMemo(() => {
    switch (codeOptions.framework) {
      case 'pytorch':
        return generatePyTorchCode(network.layers, codeOptions);
      case 'tensorflow':
      case 'keras':
        return generateTensorFlowCode(network.layers, codeOptions);
      case 'jax':
        return generateJAXCode(network.layers, codeOptions);
      default:
        return '';
    }
  }, [network.layers, codeOptions]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    toast.success('Code copied to clipboard!');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generatedCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${codeOptions.className.toLowerCase()}.py`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Code downloaded!');
  };

  return (
    <div className="h-full flex flex-col">
      <div className="p-3 border-b border-white/10 space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-medium text-white flex items-center gap-2">
            <Code2 className="w-4 h-4" />
            Code Generation
          </h3>
          <div className="flex items-center gap-1">
            <Button
              variant="ghost"
              size="sm"
              onClick={handleCopy}
              className="h-7 text-xs text-gray-400 hover:text-white"
            >
              {copied ? <Check className="w-3 h-3 mr-1" /> : <Copy className="w-3 h-3 mr-1" />}
              {copied ? 'Copied!' : 'Copy'}
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleDownload}
              className="h-7 text-xs text-gray-400 hover:text-white"
            >
              <Download className="w-3 h-3 mr-1" />
              Download
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-2">
          <div className="space-y-1">
            <Label className="text-[10px] text-gray-400">Framework</Label>
            <Select
              value={codeOptions.framework}
              onValueChange={(value: Framework) => setCodeOptions({ framework: value })}
            >
              <SelectTrigger className="h-8 bg-white/5 border-white/10 text-xs">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="bg-gray-900 border-white/10">
                <SelectItem value="pytorch">PyTorch</SelectItem>
                <SelectItem value="tensorflow">TensorFlow</SelectItem>
                <SelectItem value="jax">JAX/Flax</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1">
            <Label className="text-[10px] text-gray-400">Class Name</Label>
            <Input
              value={codeOptions.className}
              onChange={(e) => setCodeOptions({ className: e.target.value })}
              className="h-8 bg-white/5 border-white/10 text-xs"
            />
          </div>
        </div>

        <div className="flex items-center justify-between">
          <Label className="text-xs text-gray-400">Include training code</Label>
          <Switch
            checked={codeOptions.includeTraining}
            onCheckedChange={(checked) => setCodeOptions({ includeTraining: checked })}
          />
        </div>
        <div className="flex items-center justify-between">
          <Label className="text-xs text-gray-400">Include comments</Label>
          <Switch
            checked={codeOptions.includeComments}
            onCheckedChange={(checked) => setCodeOptions({ includeComments: checked })}
          />
        </div>
      </div>

      <div className="flex-1 overflow-hidden">
        <div className="h-full overflow-y-auto custom-scrollbar">
          <pre className="p-4 text-xs font-mono text-gray-300 whitespace-pre-wrap">
            {generatedCode}
          </pre>
        </div>
      </div>
    </div>
  );
}
